2021-12-02 02:25:43,921 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-6] Closed connection [connectionId{localValue:6, serverValue:5853}] to 178.128.19.31:27017 because there was a socket exception raised by this connection.
2021-12-02 02:25:43,983 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-6] No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=178.128.19.31:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond}}]}. Waiting for 30000 ms before timing out
2021-12-02 02:25:44,494 INFO com.mongodb.diagnostics.logging.SLF4JLogger [cluster-ClusterId{value='61a79ed701ca3c3ec5c3b958', description='null'}-178.128.19.31:27017] Opened connection [connectionId{localValue:8, serverValue:5878}] to 178.128.19.31:27017
2021-12-02 02:25:44,495 INFO com.mongodb.diagnostics.logging.SLF4JLogger [cluster-ClusterId{value='61a79ed701ca3c3ec5c3b958', description='null'}-178.128.19.31:27017] Monitor thread successfully connected to server with description ServerDescription{address=178.128.19.31:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=35240300, setName='reps0', canonicalAddress=127.0.0.1:27017, hosts=[127.0.0.1:27017], passives=[], arbiters=[], primary='127.0.0.1:27017', tagSet=TagSet{[]}, electionId=7fffffff000000000000000e, setVersion=1, topologyVersion=TopologyVersion{processId=61824065b32f7a93cc0ee417, counter=6}, lastWriteDate=Thu Dec 02 02:25:37 ICT 2021, lastUpdateTimeNanos=11797300750000}
2021-12-02 02:25:44,496 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-6] Closed connection [connectionId{localValue:5, serverValue:5852}] to 178.128.19.31:27017 because there was a socket exception raised on another connection from this pool.
2021-12-02 02:25:44,496 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-6] Closed connection [connectionId{localValue:3, serverValue:5850}] to 178.128.19.31:27017 because there was a socket exception raised on another connection from this pool.
2021-12-02 02:25:44,497 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-6] Closed connection [connectionId{localValue:7, serverValue:5854}] to 178.128.19.31:27017 because there was a socket exception raised on another connection from this pool.
2021-12-02 02:25:44,498 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-6] Closed connection [connectionId{localValue:4, serverValue:5851}] to 178.128.19.31:27017 because there was a socket exception raised on another connection from this pool.
2021-12-02 02:25:44,745 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-6] Opened connection [connectionId{localValue:9, serverValue:5879}] to 178.128.19.31:27017
2021-12-02 02:26:10,992 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-7] Opened connection [connectionId{localValue:10, serverValue:5880}] to 178.128.19.31:27017
2021-12-02 02:26:11,003 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-2] Opened connection [connectionId{localValue:12, serverValue:5881}] to 178.128.19.31:27017
2021-12-02 02:26:11,044 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-6] Opened connection [connectionId{localValue:11, serverValue:5882}] to 178.128.19.31:27017
2021-12-02 02:50:46,039 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-4] Closed connection [connectionId{localValue:12, serverValue:5881}] to 178.128.19.31:27017 because there was a socket exception raised by this connection.
2021-12-02 02:50:46,039 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-4] No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=178.128.19.31:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond}}]}. Waiting for 30000 ms before timing out
2021-12-02 02:50:46,611 INFO com.mongodb.diagnostics.logging.SLF4JLogger [cluster-ClusterId{value='61a79ed701ca3c3ec5c3b958', description='null'}-178.128.19.31:27017] Opened connection [connectionId{localValue:13, serverValue:5883}] to 178.128.19.31:27017
2021-12-02 02:50:46,612 INFO com.mongodb.diagnostics.logging.SLF4JLogger [cluster-ClusterId{value='61a79ed701ca3c3ec5c3b958', description='null'}-178.128.19.31:27017] Monitor thread successfully connected to server with description ServerDescription{address=178.128.19.31:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=35019800, setName='reps0', canonicalAddress=127.0.0.1:27017, hosts=[127.0.0.1:27017], passives=[], arbiters=[], primary='127.0.0.1:27017', tagSet=TagSet{[]}, electionId=7fffffff000000000000000e, setVersion=1, topologyVersion=TopologyVersion{processId=61824065b32f7a93cc0ee417, counter=6}, lastWriteDate=Thu Dec 02 02:50:37 ICT 2021, lastUpdateTimeNanos=13299418525000}
2021-12-02 02:50:46,612 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-4] Closed connection [connectionId{localValue:9, serverValue:5879}] to 178.128.19.31:27017 because there was a socket exception raised on another connection from this pool.
2021-12-02 02:50:46,613 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-4] Closed connection [connectionId{localValue:11, serverValue:5882}] to 178.128.19.31:27017 because there was a socket exception raised on another connection from this pool.
2021-12-02 02:50:46,613 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-4] Closed connection [connectionId{localValue:10, serverValue:5880}] to 178.128.19.31:27017 because there was a socket exception raised on another connection from this pool.
2021-12-02 02:50:46,886 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-4] Opened connection [connectionId{localValue:14, serverValue:5884}] to 178.128.19.31:27017
2021-12-02 02:51:06,567 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-5] Opened connection [connectionId{localValue:15, serverValue:5885}] to 178.128.19.31:27017
2021-12-02 02:51:06,628 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-4] Opened connection [connectionId{localValue:16, serverValue:5886}] to 178.128.19.31:27017
2021-12-02 03:34:51,484 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-5] Opened connection [connectionId{localValue:17, serverValue:5887}] to 178.128.19.31:27017
2021-12-02 03:37:18,555 INFO com.mongodb.diagnostics.logging.SLF4JLogger [http-nio-8091-exec-7] Opened connection [connectionId{localValue:18, serverValue:5888}] to 178.128.19.31:27017
